// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojemdrchojytqaehlldt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qZW1kcmNob2p5dHFhZWhsbGR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4NDA3NzgsImV4cCI6MjA1NTQxNjc3OH0.k-Jm5tR9NtYzjLXxm9hWzezet_Yso8sOQJ0dVU9Am9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);